# -*- coding: utf-8 -*-
#
import os
import re
import sys
sys.path.insert(0, os.path.abspath('../..'))

# -- Project information -----------------------------------------------------

project = 'nctoolkit'
copyright = '2025, Robert Wilson'
author = 'Robert Wilson'

# The short X.Y version
# The full version, including alpha/beta/rc tags
#
# Read directly from setup.py rather than hardcoding it here, so this
# doesn't quietly go stale after a release (as it previously did - this
# was still '1.2.5' well after the package had moved past 1.3).
try:
    _setup_py = os.path.join(os.path.abspath('../..'), 'setup.py')
    with open(_setup_py) as _f:
        version = re.search(r"version\s*=\s*'([^']+)'", _f.read()).group(1)
except Exception:
    version = '0.0.0'

# -- General configuration ---------------------------------------------------

# If your documentation needs a minimal Sphinx version, state it here.
#
# needs_sphinx = '1.0'

# Add any Sphinx extension module names here, as strings. They can be
# extensions coming with Sphinx (named 'sphinx.ext.*') or your custom
# ones.
extensions = [
    "sphinx.ext.autodoc",
    "sphinx.ext.autosummary",
    "sphinx.ext.intersphinx",
    "sphinx.ext.extlinks",
    "sphinx.ext.mathjax",
    "sphinx.ext.napoleon",
    'sphinx.ext.todo',
    'sphinx.ext.githubpages',
    'jupyter_sphinx',
    # nbsphinx
    'nbsphinx'



]

html_theme = "sphinx_rtd_theme"

html_static_path = ['_static']
html_logo = "_static/nctoolkit_logo.jpg"

# Banner pointing readers at the new docs site (this readthedocs.org site is
# archived) - added as a JS file rather than a theme template override so it
# shows on every page regardless of whether it was built from a .rst file or
# a notebook. See _static/archived_banner.js.
html_js_files = ['archived_banner.js']

# Add any paths that contain templates here, relative to this directory.
templates_path = ['_templates']

autosummary_generate = True

utodoc_typehints = "none"

napoleon_use_param = True
napoleon_use_rtype = True

numpydoc_class_members_toctree = True
numpydoc_show_class_members = False

# The suffix(es) of source filenames.
# You can specify multiple suffix as a list of string:
#
# source_suffix = ['.rst', '.md']
source_suffix = '.rst'

# The master toctree document.
master_doc = 'index'

# The language for content autogenerated by Sphinx. Refer to documentation
# for a list of supported languages.
#
# This is also used if you do content translation via gettext catalogs.
# Usually you set "language" from the command line for these cases.
language = 'en'

# List of patterns, relative to source directory, that match files and
# directories to ignore when looking for source files.
# This pattern also affects html_static_path and html_extra_path .
exclude_patterns = ['_build', 'Thumbs.db', '.DS_Store']

# The name of the Pygments (syntax highlighting) style to use.
pygments_style = 'sphinx'
googleanalytics_id = 'G-V5H3V2BZ74' 

googleanalytics_enabled = True


# -- Options for HTML output -------------------------------------------------

# The theme to use for HTML and HTML Help pages.  See the documentation for
# a list of builtin themes.
#

# Theme options are theme-specific and customize the look and feel of a theme
# further.  For a list of options available for each theme, see the
# documentation.
#
html_theme_options = {

    'analytics_id': 'G-V5H3V2BZ74' ## 'UA-46143561-3'

        }

# Add any paths that contain custom static files (such as style sheets) here,
# relative to this directory. They are copied after the builtin static files,
# so a file named "default.css" will overwrite the builtin "default.css".
html_static_path = ['_static']
googleanalytics_id = 'G-V5H3V2BZ74' 


# Custom sidebar templates, must be a dictionary that maps document names
# to template names.
#
# The default sidebars (for documents that don't match any pattern) are
# defined by theme itself.  Builtin themes are using these templates by
# default: ``['localtoc.html', 'relations.html', 'sourcelink.html',
# 'searchbox.html']``.
#
# html_sidebars = {}

bibtex_bibfiles = ['ref.bib']


